---
title: "Body mass index"
author: "Francisco Souza"
date: "10/30/2017"
output:
  slidy_presentation: default
  ioslides_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Body mass index

The body mass index (BMI) or Quetelet index is a value derived from the mass (weight) and height of an individual. The BMI is defined as the body mass divided by the square of the body height, and is universally expressed in units of kg/m2, resulting from mass in kilograms and height in metres.

The BMI may also be determined using a table or chart which displays BMI as a function of mass and height using contour lines or colours for different BMI categories, and which may use other units of measurement (converted to metric units for the calculation).


## Details

Body mass index (BMI) is a measure of body fat based on height and weight that applies to adult men and women

Need to inform the :

- Weight (KG)
- Height (CM)


## Logic

Define server logic required to draw a histogram

- Underweight = <18.5
- Normal weight = 18.5 - 24.9 
- Overweight = 25 -29.9 
- Obesity = BMI of 30 or greater


